tasks:
  - name: echo 'init sugcon anz' # runs during prebuild
    before: |
     cd src/Project/Sugcon/SugconAnzSxa
    init: |
     npm install
    command: |
     npm run start:connected
  - name: echo 'init sugcon eu' # runs during prebuild
    before: |
     cd src/Project/Sugcon/SugconEuSxa
    init: |
     npm install
    command: |
     npm run start:connected
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
