tasks:
  - name: echo 'init sugcon anz' # runs during prebuild    
    env:
      PUBLIC_URL:$(gp url 3000)
    before: |
     cd src/Project/Sugcon/SugconAnzSxa
    init: |
     npm install
    command: |
     gp env SugconAnzSxaURL=$(gp url 3000)
     npm run start:connected
  - name: echo 'init sugcon eu' # runs during prebuild    
    env:
      PUBLIC_URL:$(gp url 3001)
    before: |
     cd src/Project/Sugcon/SugconEuSxa
    init: |
     npm install
    command: |
     gp env SugconEuSxaURL=$(gp url 3001)
     npm run start:connected
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 3001
    onOpen: open-preview
