image:
  file: .gitpod.Dockerfile
tasks:
  - name: echo 'init sugcon anz' # runs during prebuild
    before: |
     cd src/Project/Sugcon/SugconAnzSxa
    init: |
     npm install
    command: |
     SugconAnzSxaURL=$(gp url 3000)
     sed -i '/^PUBLIC_URL=/s/=.*/="SugconAnzSxaURL"/' .env
     sed -i "s@SugconAnzSxaURL@${SugconAnzSxaURL}@g" .env
     gp sync-done sugcon-anz
     npm run start:connected
  - name: echo 'init sugcon eu' # runs during prebuild
    before: |
     cd src/Project/Sugcon/SugconEuSxa
    init: |
     gp sync-await sugcon-anz
     npm install
    command: |     
     SugconEuSxaURL=$(gp url 3001)
     sed -i '/^PUBLIC_URL=/s/=.*/="SugconEuSxaURL"/' .env
     sed -i "s@SugconEuSxaURL@${SugconEuSxaURL}@g" .env
     npm run start:connected
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Sugcon Anz
    description: Sugcon Anz site
    port: 3000
    onOpen: open-browser
  - name: Sugcon EU
    description: Sugcon EU site
    port: 3001
    onOpen: open-browser
  
